
services:
  postgres:
    image: postgres
    container_name: chat-postgres
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis
    container_name: chat-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network: